In [1]:
# Inport dependencies
import pandas as pd
import os

In [2]:
# Read csv file into DataFrame
data = pd.read_csv("Resources/Google-Playstore.csv")
data.head()

,App Name,App Id,Category,Rating,Rating Count,Installs,Minimum Installs,Maximum Installs,Free,Price,...,Developer Website,Developer Email,Released,Last Updated,Content Rating,Privacy Policy,Ad Supported,In App Purchases,Editors Choice,Scraped Time
0,Gakondo,com.ishakwe.gakondo,Adventure,0.0,0.0,10+,10.0,15,True,0.0,...,https://beniyizibyose.tk/#/,jean21101999@gmail.com,"Feb 26, 2020","Feb 26, 2020",Everyone,https://beniyizibyose.tk/projects/,False,False,False,2021-06-15 20:19:35
1,Ampere Battery Info,com.webserveis.batteryinfo,Tools,4.4,64.0,"5,000+",5000.0,7662,True,0.0,...,https://webserveis.netlify.app/,webserveis@gmail.com,"May 21, 2020","May 06, 2021",Everyone,https://dev4phones.wordpress.com/licencia-de-uso/,True,False,False,2021-06-15 20:19:35
2,Vibook,com.doantiepvien.crm,Productivity,0.0,0.0,50+,50.0,58,True,0.0,...,NaN,vnacrewit@gmail.com,"Aug 9, 2019","Aug 19, 2019",Everyone,https://www.vietnamairlines.com/vn/en/terms-an...,False,False,False,2021-06-15 20:19:35
3,Smart City Trichy Public Service Vehicles 17UC...,cst.stJoseph.ug17ucs548,Communication,5.0,5.0,10+,10.0,19,True,0.0,...,http://www.climatesmarttech.com/,climatesmarttech2@gmail.com,"Sep 10, 2018","Oct 13, 2018",Everyone,NaN,True,False,False,2021-06-15 20:19:35
4,GROW.me,com.horodyski.grower,Tools,0.0,0.0,100+,100.0,478,True,0.0,...,http://www.horodyski.com.pl,rmilekhorodyski@gmail.com,"Feb 21, 2020","Nov 12, 2018",Everyone,http://www.horodyski.com.pl,False,False,False,2021-06-15 20:19:35

In [3]:
# Display the list of columns
for col in data.columns:
    print(col)

App Name
App Id
Category
Rating
Rating Count
Installs
Minimum Installs
Maximum Installs
Free
Price
Currency
Size
Minimum Android
Developer Id
Developer Website
Developer Email
Released
Last Updated
Content Rating
Privacy Policy
Ad Supported
In App Purchases
Editors Choice
Scraped Time

In [4]:
# Drop unnessasery columns
data_dropped_columns = data.drop(columns=["App Id", "Minimum Installs", "Free", "Currency", "Size", "Minimum Android", "Developer Id", "Developer Website", "Developer Email", 
"Released", "Last Updated", "Content Rating", "Privacy Policy", "In App Purchases", "Editors Choice", "Scraped Time", "Installs"])
data_dropped_columns.head()

,App Name,Category,Rating,Rating Count,Maximum Installs,Price,Ad Supported
0,Gakondo,Adventure,0.0,0.0,15,0.0,False
1,Ampere Battery Info,Tools,4.4,64.0,7662,0.0,True
2,Vibook,Productivity,0.0,0.0,58,0.0,False
3,Smart City Trichy Public Service Vehicles 17UC...,Communication,5.0,5.0,19,0.0,True
4,GROW.me,Tools,0.0,0.0,478,0.0,False

In [5]:
# Check DataFrame for NaN
data_dropped_columns.isnull().any()

App Name             True
Category            False
Rating               True
Rating Count         True
Maximum Installs    False
Price               False
Ad Supported        False
dtype: bool

In [6]:
# Check columns with not null vallues
data_dropped_columns.notnull().sum()

App Name            2312942
Category            2312944
Rating              2290061
Rating Count        2290061
Maximum Installs    2312944
Price               2312944
Ad Supported        2312944
dtype: int64

In [7]:
# Check columns with null values
data_dropped_columns.isnull().sum()

App Name                2
Category                0
Rating              22883
Rating Count        22883
Maximum Installs        0
Price                   0
Ad Supported            0
dtype: int64

In [8]:
# Drop columns with null values
data_dropped_nulls = data_dropped_columns.dropna()
data_dropped_nulls

,App Name,Category,Rating,Rating Count,Maximum Installs,Price,Ad Supported
0,Gakondo,Adventure,0.0,0.0,15,0.0,False
1,Ampere Battery Info,Tools,4.4,64.0,7662,0.0,True
2,Vibook,Productivity,0.0,0.0,58,0.0,False
3,Smart City Trichy Public Service Vehicles 17UC...,Communication,5.0,5.0,19,0.0,True
4,GROW.me,Tools,0.0,0.0,478,0.0,False
...,...,...,...,...,...,...,...
2312939,å¤§ä¿ å®¢â€”ç†±è¡€æ­¸ä¾†,Role Playing,4.3,16775.0,337109,0.0,False
2312940,ORU Online,Education,0.0,0.0,430,0.0,False
2312941,Data Structure,Education,0.0,0.0,202,0.0,False
2312942,Devi Suktam,Music & Audio,3.5,8.0,2635,0.0,True
2312943,Biliyor Musun - Sonsuz YarÄ±ÅŸ,Trivia,5.0,12.0,354,0.0,True

In [9]:
# Check if new DataFrame still has null values
data_dropped_nulls.notnull().sum()

App Name            2290059
Category            2290059
Rating              2290059
Rating Count        2290059
Maximum Installs    2290059
Price               2290059
Ad Supported        2290059
dtype: int64

In [10]:
# Replace spaces with underscores, change all letters to lowercase, and changer ad supported to numeric data
data_dropped_nulls.columns = [i.replace(' ', '_') for i in data_dropped_nulls]
clean_google_playstore_df = data_dropped_nulls.rename(columns=str.lower)
clean_google_playstore_df["ad_supported"] = clean_google_playstore_df["ad_supported"].astype(int)
clean_google_playstore_df

,app_name,category,rating,rating_count,maximum_installs,price,ad_supported
0,Gakondo,Adventure,0.0,0.0,15,0.0,0
1,Ampere Battery Info,Tools,4.4,64.0,7662,0.0,1
2,Vibook,Productivity,0.0,0.0,58,0.0,0
3,Smart City Trichy Public Service Vehicles 17UC...,Communication,5.0,5.0,19,0.0,1
4,GROW.me,Tools,0.0,0.0,478,0.0,0
...,...,...,...,...,...,...,...
2312939,å¤§ä¿ å®¢â€”ç†±è¡€æ­¸ä¾†,Role Playing,4.3,16775.0,337109,0.0,0
2312940,ORU Online,Education,0.0,0.0,430,0.0,0
2312941,Data Structure,Education,0.0,0.0,202,0.0,0
2312942,Devi Suktam,Music & Audio,3.5,8.0,2635,0.0,1
2312943,Biliyor Musun - Sonsuz YarÄ±ÅŸ,Trivia,5.0,12.0,354,0.0,1

In [11]:
clean_google_playstore_df.to_csv('Resources/clean_google_playstore.csv', index=False)

In [12]:
# Create category id dataframe and csv
category_ids_df = pd.DataFrame(clean_google_playstore_df["category"].unique())
category_ids_df.insert(1, "category_id", range(1, 49))
category_ids_df.columns = ["category", "category_id"]
category_ids_df["category_id"] = category_ids_df["category_id"].astype(str).str.zfill(3)
category_ids_df.to_csv("Resources/category_id.csv", index=False)
category_ids_df

                   category category_id
0                 Adventure         001
1                     Tools         002
2              Productivity         003
3             Communication         004
4                    Social         005
5          Libraries & Demo         006
6                 Lifestyle         007
7           Personalization         008
8                    Racing         009
9         Maps & Navigation         010
10           Travel & Local         011
11             Food & Drink         012
12        Books & Reference         013
13                  Medical         014
14                   Puzzle         015
15            Entertainment         016
16                   Arcade         017
17          Auto & Vehicles         018
18              Photography         019
19         Health & Fitness         020
20                Education         021
21                 Shopping         022
22                    Board         023
23            Music & Audio         024
24                   Sports         025
25                   Beauty         026
26                 Business         027
27              Educational         028
28                  Finance         029
29         News & Magazines         030
30                   Casual         031
31             Art & Design         032
32             House & Home         033
33                     Card         034
34                   Events         035
35                   Trivia         036
36                  Weather         037
37                 Strategy         038
38                     Word         039
39  Video Players & Editors         040
40                   Action         041
41               Simulation         042
42                    Music         043
43                   Dating         044
44             Role Playing         045
45                   Casino         046
46                   Comics         047
47                Parenting         048

In [13]:
# Create app install csv
app_install_df = clean_google_playstore_df.drop(columns=["category", "rating", "rating_count"])
app_install_df.to_csv("Resources/app_install_df.csv")
app_install_df.head()

,app_name,maximum_installs,price,ad_supported
0,Gakondo,15,0.0,0
1,Ampere Battery Info,7662,0.0,1
2,Vibook,58,0.0,0
3,Smart City Trichy Public Service Vehicles 17UC...,19,0.0,1
4,GROW.me,478,0.0,0

In [14]:
# Create google app info csv
google_app_info_df = clean_google_playstore_df.drop(columns=["maximum_installs", "ad_supported"])
google_app_info_df.to_csv("Resources/google_app_info.csv")
google_app_info_df.head()

,app_name,category,rating,rating_count,price
0,Gakondo,Adventure,0.0,0.0,0.0
1,Ampere Battery Info,Tools,4.4,64.0,0.0
2,Vibook,Productivity,0.0,0.0,0.0
3,Smart City Trichy Public Service Vehicles 17UC...,Communication,5.0,5.0,0.0
4,GROW.me,Tools,0.0,0.0,0.0

In [27]:
# Import dependencies to connect to database
import sqlalchemy 
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker
from sqlalchemy_utils import database_exists, create_database
from local_settings import postgresql as settings

In [18]:
# Create function for get engine
def get_engine(user, passwd, host, port, db):
    url = f"postgresql://{user}:{passwd}@{host}:{port}/{db}"
    engine = create_engine(url, pool_size=50, echo=False)
    return engine

In [19]:
# Create engine
engine = get_engine(settings['pguser'],
                    settings['pgpasswd'],
                    settings['pghost'],
                    settings['pgport'],
                    settings['pgdb'])

In [20]:
engine.url

postgresql://postgres:***@localhost:5432/postgres

In [21]:
# Function to create engine
def get_engine_from_settings():
    keys = ['pguser', 'pgpasswd', 'pghost', 'pgport', 'pgdb']
    if not all(key in keys for key in settings.keys()):
        raise Exception('Bad config file')

    return get_engine(settings['pguser'],
                    settings['pgpasswd'],
                    settings['pghost'],
                    settings['pgport'],
                    settings['pgdb'])

In [22]:
# Function to create session
def get_session():
    engine = get_engine_from_settings()
    session = sessionmaker(bind=engine)()
    return session

In [24]:
# Create session
session = get_session()